{% set name = "deicode" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 46f582228ab3dd271ce5e1c3f736339c75d1059f0cee7d09d6f168627dc8621c

build:
  skip: true  # [win or py2k]
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed" 

requirements:

  host:
    - python
    - pip
    - numpy >=1.12.1

  run:
    - python
    - numpy >=1.12.1
    - pandas >=0.10.0
    - scipy >=0.19.1
    - nose >=1.3.7
    - scikit-bio >=0.5.4
    - h5py
    - click
    - Cython >=0.23

test:
  imports:
    - deicode

about:
  home: https://github.com/cameronmartino/DEICODE
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING.txt
  summary: 'Robust Aitchison compositional biplots from sparse count data'

extra:
    recipe-maintainers:
        - cameronmartino
